# Generated by Django 5.2.8 on 2025-11-30 02:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_sellrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('created_by', 'sku')},
        ),
    ]
